name: Build and Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Log in to Azure Container Registry
      run: echo "k8/2hMfAeKsdRvF18yAUcBzaybLD1kpBaYBRiLsUXy+ACRC/PGC8" | docker login k8autopilot.azurecr.io -u k8autopilot --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t k8autopilot.azurecr.io/react-app:${{ github.sha }} .
        docker push k8autopilot.azurecr.io/react-app:${{ github.sha }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yaml
      env:
        KUBECONFIG: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: <your-certificate-authority-data>
              server: https://<your-aks-server>
            name: aks-cluster
          contexts:
          - context:
              cluster: aks-cluster
              user: clusterUser
            name: aks-context
          current-context: aks-context
          kind: Config
          preferences: {}
          users:
          - name: clusterUser
            user:
              token: <your-token>
