name: Build and Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Log in to Azure Container Registry
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login <your-acr-name>.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t <your-acr-name>.azurecr.io/react-app:${{ github.sha }} .
        docker push <your-acr-name>.azurecr.io/react-app:${{ github.sha }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
